version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_v1
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=user1
  django_gunicorn:
    env_file: 
      - .env
    build:
      context: .
    ports: 
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
